JustGive/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JustGive.Models
{
    public class Donation
    {
        public int DonationId { get; set; }

        [Required(ErrorMessage = "The title must exist")]
        [MinLength(3, ErrorMessage = "Title cannot be less than 3 characters!"),
            MaxLength(70, ErrorMessage = "Title cannot be more than 70 characters!")]
        [RegularExpression(@"^[A-Z].*$", ErrorMessage = "The title must start with an uppercase!")]
        public String Title { get; set; }

        [Required(ErrorMessage = "The description must exist")]
        [MinLength(5, ErrorMessage = "Description cannot be less than 5 characters!"),
            MaxLength(200, ErrorMessage = "Description cannot be more than 200 characters!")]
        public String Description { get; set; }
        //one-to-many
        [Required(ErrorMessage ="The location must be selected")]
        public int LocationId { get; set; }
        public virtual Location Location { get; set; }
        // many-to-many
        public virtual ICollection<Tag> Tags { get; set; }
        //one-to-many
        
        public virtual Cause Cause { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public bool IsDonated { get; set; } = false;
        //list for choosing the location
        [NotMapped]
        public IEnumerable<SelectListItem> LocationList { get; set; }
        //list for choosing the cause
        [NotMapped]
        public IEnumerable<SelectListItem> CauseList { get; set; }
        //checkbox for many-to-many-relationship
        [NotMapped]
        public List<TagDonationViewModel> TagList { get; set; }

    }
}

JustGive/Controllers/CauseController.cs
using JustGive.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JustGive.Controllers
{
    [Authorize]
    public class CauseController : Controller
    {
        private Models.ApplicationDbContext db = new ApplicationDbContext();
        // GET: Cause
        [AllowAnonymous]
        public ActionResult Index()
        {
            List<Cause> causes = db.Causes.Include("ContactInfo").ToList();
            ViewBag.Causes = causes;
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                Cause cause = db.Causes.Include("Location").SingleOrDefault(c => c.CauseId == id);

                if (cause != null)
                {
                    ViewBag.UserId = User.Identity.GetUserId();
                    return View(cause);
                }
                return HttpNotFound("Couldn't find the cause with id " + id.ToString());
            }
            return HttpNotFound("Missing cause id!");
        }

        [HttpGet]
        [Authorize(Roles = "Donator, Admin")]
        public ActionResult New()
        {
            CauseContactViewModel causeContact = new CauseContactViewModel();
            causeContact.Cause = new Cause();
            causeContact.ContactInfo = new ContactInfo();
            causeContact.Cause.TagList = GetAllTags();
            causeContact.Cause.LocationList = getAllLocations();
            causeContact.Cause.Tags = new List<Tag>();
            return View(causeContact);
        }
        
        [HttpPost]
        [Authorize(Roles = "Donator, Admin")]
        public ActionResult New(CauseContactViewModel causeContact)
        {
            
            try
            {
                causeContact.Cause.LocationList = getAllLocations();
                ModelState.Remove("Cause.ContactInfo");

                if (ModelState.IsValid)
                {
                    ContactInfo contactInfo = new ContactInfo
                    {
                        Name = causeContact.ContactInfo.Name,
                        PhoneNumber = causeContact.ContactInfo.PhoneNumber,
                        BirthDate = causeContact.ContactInfo.BirthDate
                    };

                    Cause cause = new Cause
                    {
                        Title = causeContact.Cause.Title,
                        Description = causeContact.Cause.Description,
                        LocationId = causeContact.Cause.LocationId,
                        ContactInfo = contactInfo,
                        UserId = User.Identity.GetUserId(),
                        Tags = new List<Tag>(),
                        LocationList = getAllLocations()
                    };
                    contactInfo.Cause = cause;

                    //save the selected tags
                    var selectedTags = causeContact.Cause.TagList.
                        Where(b => b.IsChecked).ToList();
                    
                    db.ContactInfos.Add(contactInfo);
                    
                    
                    for (int i = 0; i < selectedTags.Count(); i++)
                    {
                        //asign to the donation the selected tags
                        Tag tag = db.Tags.Find(selectedTags[i].Id);
                        cause.Tags.Add(tag);
                    }
                    db.Causes.Add(cause);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(causeContact);
            }
            catch (Exception e)
            {
                return View(causeContact);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Donator, Admin")]
        public ActionResult Edit(int ?id)
        {
            if (id.HasValue)
            {
                Cause cause = db.Causes.Find(id);
                if (cause != null)
                {
                    if (User.Identity.GetUserId() == cause.UserId || User.IsInRole("Admin"))
                    {
                        cause.LocationList = getAllLocations();
                        cause.TagList = GetAllTags();
                        foreach (Tag tagChecked in cause.Tags)
                        {
                            //update the checkbox list
                            cause.TagList.FirstOrDefault(t => t.Id == tagChecked.TagId).IsChecked = true;
                        }

                        CauseContactViewModel causeContact = new CauseContactViewModel();
                        causeContact.Cause = cause;
                        causeContact.ContactInfo = cause.ContactInfo;
                        return View(causeContact);
                    }
                    return RedirectToAction("Index");
                }
                return HttpNotFound("Couldn't find the cause id " + id.ToString());
            }
            return HttpNotFound("Missing the cause id");
        }

        [HttpPut]
        [Authorize(Roles = "Donator, Admin")]
        public ActionResult Edit(int id, CauseContactViewModel causeContactReq)
        {
            //save the tags that where selected into the form
            var selectedTags = causeContactReq.Cause.TagList.Where(t => t.IsChecked).ToList();
            causeContactReq.Cause.LocationList = getAllLocations();
            try
            {
                ModelState.Remove("Cause.ContactInfo");
                if (ModelState.IsValid)
                { 
                    Cause cause = db.Causes.Include("Location").
                        SingleOrDefault(c => c.CauseId.Equals(id));
                    if (TryUpdateModel(cause))
                    {
                        cause.Title = causeContactReq.Cause.Title;
                        cause.Description = causeContactReq.Cause.Description;
                        cause.LocationId = causeContactReq.Cause.LocationId;
                        cause.Donations = causeContactReq.Cause.Donations;
                        cause.Tags.Clear();
                        cause.Tags = new List<Tag>();

                        for (int i = 0; i < selectedTags.Count(); ++i)
                        {
                            Tag tag = db.Tags.Find(selectedTags[i].Id);
                            cause.Tags.Add(tag);
                        }
                        db.SaveChanges();
                    }
                    ContactInfo contactInfo = db.ContactInfos.Find(cause.ContactInfo.Id);
                    if (TryUpdateModel(contactInfo))
                    {
                        contactInfo.Name = causeContactReq.ContactInfo.Name;
                        contactInfo.PhoneNumber = causeContactReq.ContactInfo.PhoneNumber;
                        contactInfo.BirthDate = causeContactReq.ContactInfo.BirthDate;
                    }
                    return RedirectToAction("Index");
                }
                return View(causeContactReq);
            }
            catch (Exception e)
            {
                return View(causeContactReq);
            }
        }


        [HttpDelete]
        [Authorize(Roles = "Donator, Admin")]
        public ActionResult Delete(int? id)
        {
            if(id.HasValue)
            {
                Cause cause = db.Causes.Find(id);
                if(cause != null)
                {
                    if (User.Identity.GetUserId() == cause.UserId || User.IsInRole("Admin"))
                    {
                        db.ContactInfos.Remove(cause.ContactInfo);
                        db.Causes.Remove(cause);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return RedirectToAction("Index");
                    
                }
                return HttpNotFound("Couldn't find the cause id " + id.ToString());
            }
            return HttpNotFound("Missing id parameter");
        }


        [NonAction]
        private IEnumerable<SelectListItem> getAllLocations()
        {
            var selectedList = new List<SelectListItem>();
            foreach (var location in db.Locations.ToList())
            {
                selectedList.Add(new SelectListItem
                {
                    Value = location.LocationId.ToString(),
                    Text = location.City + ", " + location.Country
                });
            }
            return selectedList;
        }

        [NonAction]
        private List<TagDonationViewModel> GetAllTags()
        {
            var checkboxList = new List<TagDonationViewModel>();
            foreach (var tag in db.Tags.ToList())
            {
                checkboxList.Add(new TagDonationViewModel
                {
                    Id = tag.TagId,
                    Name = tag.Name,
                    IsChecked = false
                });
            }
            return checkboxList;
        }
    }
}

JustGive/Views/Donation/AddToCause.cshtml
@{
    ViewBag.Title = "Choose a Cause";
}

<h2>@ViewBag.Title</h2>

<br />

@Html.ActionLink("See causes details", "Index", "Cause")

<br />
<br />

@foreach (var cause in ViewBag.Causes)
{
    <div class="panel panel-default">
        <div class="panel-body">
            @Html.Label("Title", "Title:")
            <br />
            <p>@cause.Title</p>

            @Html.Label("Description", "Description:")
            <br />
            <p>@cause.Description</p>
            @using (Html.BeginForm(actionName: "ChooseCause", controllerName: "Donation", method: FormMethod.Post, routeValues: new { donationId = ViewBag.DonationId, causeId = cause.CauseId }))
            {
                @Html.HttpMethodOverride(HttpVerbs.Put)
                <button class="btn btn-primary col-lg-2" style="margin-right:5px" type="submit">Donate!</button>
            }
        </div>
    </div>
}

JustGive/Views/Donation/Details.cshtml
@model JustGive.Models.Donation
@{
    ViewBag.Title = "Donation Details";
}
@if (Model.IsDonated == true)
{
    <h2>@ViewBag.Title - <em>Donated</em></h2>
}
else
{
    <h2>@ViewBag.Title</h2>
}

@Html.LabelFor(d => d.Title)
<br />
<p>@Model.Title</p>
<br />
@Html.LabelFor(d => d.Description)
<br />
<p>@Model.Description</p>
@if (Model.Tags.Count > 0)
{
    @Html.Label("Tags", "Tags:")
    <br />
    <ul>
        @foreach (var tag in Model.Tags)
        {
            <li> @tag.Name</li>
        }
    </ul>
}
<br />
@if (@Model.Location != null)
{
    @Html.LabelFor(d => d.Location)
    <br />
    @Html.LabelFor(d => d.Location.City)
    <p>@Model.Location.City</p>
    @Html.LabelFor(d => d.Location.Country)
    <p>@Model.Location.Country</p>
}

<p>Created by @Model.User.UserName</p>

@if (ViewBag.UserId == Model.UserId || User.IsInRole("Admin"))
{
    <br />
    using (Html.BeginForm(actionName: "Edit", controllerName: "Donation", method: FormMethod.Get, routeValues: new { id = Model.DonationId }))
    {
        <button class="btn btn-primary col-lg-2" style="margin-right:5px" type="submit">Edit</button>
    }
    <br />
    <br />
    using (Html.BeginForm(actionName: "Delete", controllerName: "Donation", method: FormMethod.Post, routeValues: new { id = Model.DonationId }))
    {
        @Html.HttpMethodOverride(HttpVerbs.Delete)
        <button class="btn btn-primary col-lg-2" style="margin-right:5px" type="submit">Delete</button>
    }
    <br />
    if (Model.IsDonated == false)
    {
        <br />
        using (Html.BeginForm(actionName: "AddToCause", controllerName: "Donation", method: FormMethod.Get, routeValues: new { id = Model.DonationId }))
        {
            <button class="btn btn-primary col-lg-2" style="margin-right:5px" type="submit">Donate to a cause</button>
        }
    }
}
<br />

JustGive/Views/Donation/Edit.cshtml
@model JustGive.Models.Donation
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm(actionName: "Edit", controllerName: "Donation", method: FormMethod.Post))
{
    @Html.HttpMethodOverride(HttpVerbs.Put)
    @Html.HiddenFor(d => d.DonationId)
    <br />
    @Html.Label("Title", "Title:")
    <br />
    @Html.EditorFor(d => d.Title, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(d => d.Title, "", new { @class = "text-danger" })
    <br />
    @Html.Label("Description", "Description:")
    @Html.TextAreaFor(d => d.Description, new { @class = "form-control", @rows = "10" })
    @Html.ValidationMessageFor(d => d.Description, "", new { @class = "text-danger" })
    <br />
    @Html.Label("Location", "Location:")
    <br />
    @Html.DropDownListFor(d => d.LocationId, new SelectList(Model.LocationList, "Value", "Text"), "Choose a location", new { @class = "form-control" })
    @Html.ValidationMessageFor(d => d.LocationId, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(d => d.TagList, "Choose tags:")
    <br />
    for (int i = 0; i < Model.TagList.Count(); i++)
    {
        @Html.HiddenFor(d => d.TagList[i].Id)
        @Html.HiddenFor(d => d.TagList[i].Name)
        @Html.CheckBoxFor(d => d.TagList[i].IsChecked)
        @Html.DisplayFor(d => d.TagList[i].Name)
        <br />
    }
    <br />
    <button class="btn btn-primary" type="submit">Update</button>
}

JustGive/Views/Donation/Index.cshtml
@{
    ViewBag.Title = "Available Donations";
}

<h2>@ViewBag.Title</h2>

@foreach (var donation in ViewBag.Donations)
{
    <div class="panel panel-default">
        <div class="panel-body">
            @Html.Label("Title", "Title:")
            <br />
            @if (@donation.IsDonated == true)
            {
                <p>@donation.Title - <em>Donated</em></p>
            }
            else
            {
                <p>@donation.Title</p>
            }

            @Html.Label("Description", "Description:")
            <br />
            <p>@donation.Description</p>
            @using (Html.BeginForm(actionName: "Details", controllerName: "Donation",
                    method: FormMethod.Get, routeValues: new { id = donation.DonationId }))
            {
                <button class=" btn btn-primary">Details</button>
            }
        </div>
    </div>
}

@using (Html.BeginForm(actionName: "New", controllerName: "Donation", method: FormMethod.Get))
{
    <button class="btn btn-primary">Add new Donation</button>
}

JustGive/Views/Donation/New.cshtml
@model JustGive.Models.Donation
@{
    ViewBag.Title = "Add Donation";
}

<h2>@ViewBag.Title</h2>
<br />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm(actionName: "New", controllerName: "Donation", method: FormMethod.Post))
        {
            @Html.LabelFor(d => d.Title)
            <br />
            @Html.TextBoxFor(d => d.Title, null,
                            new { placeholder = "Type in the donation's title", @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Title, "", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.Description)
            @Html.TextAreaFor(d => d.Description,
                            new { placeholder = "Type in the donation's summary", @class = "form-control", @rows = "10" })
            @Html.ValidationMessageFor(d => d.Description, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Location", "Location:")
            <br />
            @Html.DropDownListFor(d => d.LocationId, new SelectList(Model.LocationList, "Value", "Text"), "Choose a location", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.LocationId, "", new { @class = "text-danger" })

            <br />
            @Html.LabelFor(b => b.TagList, "Choose tags:")
            <br />
            for (int i = 0; i < Model.TagList.Count(); i++)
            {
                @Html.HiddenFor(b => b.TagList[i].Id)
                @Html.HiddenFor(b => b.TagList[i].Name)
                @Html.CheckBoxFor(b => b.TagList[i].IsChecked)
                @Html.DisplayFor(b => b.TagList[i].Name)
                <br />
            }
            <br />
            <button class="btn btn-primary" type="submit">Add</button>
        }

    </div>
    <div class="col-md-4" style="position: absolute; top: 0; bottom: 0; left: 0; right: 0; margin: auto;">
        <div style="padding-top: 490px;margin: auto; width: 50%;">
            @using (Html.BeginForm(actionName: "New", controllerName: "Location", method: FormMethod.Get))
            {
                <button class="btn btn-primary" type="submit">Add new location</button>
            }
        </div>
        <div style="padding-top: 70px;margin: auto; width: 50%;">
            @using (Html.BeginForm(actionName: "New", controllerName: "Tag", method: FormMethod.Get))
            {
                <button class="btn btn-primary" type="submit">Add new tag</button>
            }
        </div>
    </div>
</div>